spring: 
  profiles: 
    active: 
    - dev
--- 
spring: 
  profiles: dev #开发环境
  application: 
    name: springclouddemo-config-lee-dev
--- 
spring: 
  profiles: test #测试环境
  application: 
    name: springclouddemo-config-lee-test
#请保存为UTF8格式